# Generated by Django 4.2.26 on 2025-12-07 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tarefas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tarefa',
            old_name='status',
            new_name='concluida',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='data',
        ),
        migrations.RemoveField(
            model_name='tarefa',
            name='usuario',
        ),
    ]
